# API Info
served-model-name: deepseek-v32
tool-call-parser: deepseekv32
reasoning-parser: deepseek-v3
enable-cache-report: true
# Server Info
host: 0.0.0.0
# Model Info
model-path: /models/DeepSeek-V3.2
trust-remote-code: true
# Memory Management
mem-fraction-static: 0.8
max-running-requests: 64
context-length: 131072
chunked-prefill-size: 8192
# Parallel
tp: 8
# Speculative Decode
speculative-algorithm: EAGLE
speculative-num-steps: 2
speculative-eagle-topk: 1
speculative-num-draft-tokens: 3
# Other
watchdog-timeout: 1000000

