# API Info
served-model-name: GLM-5.1
tool-call-parser: glm47
reasoning-parser: glm45
enable-cache-report: true
# Server Info
host: 0.0.0.0
# Model Info
model-path: /models/GLM-5.1-FP8
trust-remote-code: true
# Memory Management
mem-fraction-static: 0.8
max-running-requests: 64
cuda-graph-max-bs: 32
# Parallel
tp: 8
ep: 8
dp: 8
enable-dp-attention: true
enable-dp-lm-head: true
moe-dense-tp-size: 1
# Attention
page-size: 64
attention-backend: nsa
nsa-decode-backend: flashmla_kv
kv-cache-dtype: fp8_e4m3
# MoE
moe-a2a-backend: deepep
deepep-mode: low_latency
# PD Disaggregation
disaggregation-mode: decode
disaggregation-ib-device: mlx5_0,mlx5_1,mlx5_2,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_7
# Speculative Decode
speculative-algorithm: EAGLE
speculative-num-steps: 2
speculative-eagle-topk: 1
speculative-num-draft-tokens: 3
# Other
watchdog-timeout: 1000000

