# API Info
served-model-name: deepseek-v32
tool-call-parser: deepseekv32
reasoning-parser: deepseek-v3
enable-cache-report: true
# Server Info
host: 0.0.0.0
# Model Info
model-path: /models/DeepSeek-V3.2
trust-remote-code: true
# Memory Management
mem-fraction-static: 0.8
max-running-requests: 64
chunked-prefill-size: 8192
disable-cuda-graph: true
# Parallel
tp: 8
ep: 8
dp: 8
enable-dp-attention: true
load-balance-method: round_robin
# Attention
attention-backend: nsa
nsa-prefill-backend: flashmla_auto
kv-cache-dtype: fp8_e4m3
page-size: 64
# MoE
moe-a2a-backend: deepep
deepep-mode: normal
# PD Disaggregation
disaggregation-mode: prefill
disaggregation-ib-device: mlx5_0,mlx5_1,mlx5_2,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_7
# Other
watchdog-timeout: 1000000

